# Generated by Django 3.0.1 on 2020-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='group_members',
            field=models.ManyToManyField(to='chat.Participants'),
        ),
    ]
