# Generated by Django 3.1.1 on 2020-10-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20201010_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_group', to='chat.rooms'),
        ),
    ]
