# Generated by Django 3.1.1 on 2020-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20201010_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='related_group',
        ),
        migrations.AddField(
            model_name='message',
            name='group_name',
            field=models.CharField(default='family', max_length=256),
        ),
    ]
